name: refresh-resolvers

on:
  schedule:
  # Run daily
    - cron:  '0 0 * * *'

jobs:
  resfresh-list:
    runs-on: ubuntu-20.04
    steps:

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
    
      - name: checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout DNS Validator
        uses: actions/checkout@v2
        with:
          repository: 'bug4fix/dnsvalidator'
          path: dnsvalidator
    
      - name: Install DNS Validator
        run: |
          cd dnsvalidator
          python3 setup.py install
      
      - name: Install contextvars
        run: pip3 install contextvars

      - name: Install importlib-metadata
        run: pip3 install importlib-metadata
    
      - name: Generate new resolvers
        run: dnsvalidator -tL https://gist.githubusercontent.com/bug4fix/238dbe81cf8354a40ff80147bef7170b/raw/c8aa39de03d3b800ab21ca73a2cbd5784821aa6e/nameservers.txt -threads 40 --silent > resolvers.txt
    
      - name: Set current date
        run: echo "NOW=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      
      - name: Commit changes
        run: |
          git config --local user.email "bot@github.com"
          git config --local user.name "[bot] github-actions"
          git add resolvers.txt
          git commit -m "${NOW} update"
    
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
